services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports: ["6541:5432"]
    volumes: [stats-db-data:/var/lib/postgresql/data]

  stats-server:
    build: ./stats-service/server          # точный путь
    container_name: stats-server-container
    depends_on: [stats-db]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    ports: ["9090:9090"]

  # ---------- main ----------
  main-db:
    image: postgres:16.1
    container_name: main-db-container
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports: ["6540:5432"]
    volumes: [main-db-data:/var/lib/postgresql/data]

  ewm-service:
    build: ./ewm-main-service
    container_name: ewm-service-container
    depends_on:
      - main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm_main
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS_SERVICE_URL=http://stats-server:9090
    ports: ["8080:8080"]

volumes:
  stats-db-data:
  main-db-data:
